services:
  keycloak:
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "true"
      KC_PROXY_HEADERS: xforwarded
      APP_ORIGIN: ${APP_ORIGIN}
    command: ["start", "--import-realm"]
    volumes:
      - ${PWD}/keycloak/import:/opt/keycloak/data/import:ro
      - ${PWD}/keycloak/themes:/opt/keycloak/themes:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multiapp-backend
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: demo-prod
      APP_DB_URL: jdbc:postgresql://postgres:5432/${APP_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      OIDC_ISSUER_URI: ${OIDC_ISSUER_URI}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_UPLOAD_DIR: ${APP_UPLOAD_DIR:-/data/uploads}
      APP_DEMO_SEED_ENABLED: ${APP_DEMO_SEED_ENABLED:-true}
      APP_DEMO_SEED_VERSION: ${APP_DEMO_SEED_VERSION:-v1}
      APP_PLATFORM_ADMIN_TENANT: ${APP_PLATFORM_ADMIN_TENANT:-__platform_admin}
    volumes:
#      - 真实vps上应该使用
#      -
#      - /opt/multiapp/uploads:/data/uploads
      - ${PWD}/keycloak/import:/app/keycloak/import:ro
      - app_uploads:/data/uploads
    expose:
      - "8081"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:8081/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
  caddy:
    image: caddy:2.8
    container_name: multiapp-caddy
    depends_on:
      - backend
      - keycloak
    networks:
      default:
        aliases:
          - auth.localhost
          - api.localhost
          - app.localhost
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /Users/jiezhang/Desktop/frontmultiapp/dist:/srv/multiapp-frontend:ro
    restart: unless-stopped
